<?php
add_action('acf/init', 'register_acf_blocks');
function register_acf_blocks()
{
    if (!function_exists('acf_register_block_type')) return;

    $blocks = [
        [
            'name'        => 'cta_block',
            'title'       => __('Call to Action'),
            'description' => __('A custom CTA block.'),
            'template'    => '/template-parts/blocks/cta/cta_block.php',
            'icon'        => 'megaphone',
            'keywords'    => ['cta', 'call to action'],
        ],
        [
            'name'        => 'cta_button_block',
            'title'       => __('Call to Action Buttons'),
            'description' => __('Add multiple CTA Buttons.'),
            'template'    => '/template-parts/blocks/cta/cta_button_block.php',
            'icon'        => 'megaphone',
            'keywords'    => ['cta buttons', 'call to action', 'cta', 'buttons'],
        ],
        [
            'name'        => 'video_hero',
            'title'       => __('Video Hero'),
            'description' => __('A custom Video Hero block.'),
            'template'    => '/template-parts/blocks/hero/video_hero.php',
            'icon'        => 'format-video',
            'keywords'    => ['hero', 'banner', 'video'],
        ],
        [
            'name'        => 'cards',
            'title'       => __('Cards'),
            'description' => __('A customizable Card block.'),
            'template'    => '/template-parts/blocks/cards/cards.php',
            'icon'        => 'columns',
            'keywords'    => ['cards'],
        ],
        [
            'name'        => 'cards_central_image',
            'title'       => __('Cards with Central Image'),
            'description' => __('Four cards around a central image.'),
            'template'    => '/template-parts/blocks/cards/cards_central_image.php',
            'icon'        => 'columns',
            'keywords'    => ['cards', 'central image', 'cards with image', 'four cards'],
        ],
        [
            'name'        => 'flip_cards',
            'title'       => __('Flip Cards'),
            'description' => __('Three to Nine cards with a flipping animation.'),
            'template'    => '/template-parts/blocks/cards/flip_cards.php',
            'icon'        => 'image-rotate',
            'keywords'    => ['cards', 'flip cards', 'colored cards', 'grid'],
        ],
        [
            'name'        => 'cirlce_cards',
            'title'       => __('Circle Cards'),
            'description' => __('Circle Cards with colored background and white text.'),
            'template'    => '/template-parts/blocks/cards/circle_cards.php',
            'icon'        => 'info',
            'keywords'    => ['cards', 'circle cards'],
        ],
        [
            'name'        => 'post_display',
            'title'       => __('Post Display'),
            'description' => __('A customized Post Display block.'),
            'template'    => '/template-parts/blocks/post-displays/post_display.php',
            'icon'        => 'images-alt2',
            'keywords'    => ['post', 'display']
        ],
        [
            'name'        => 'testimonial_slider',
            'title'       => __('Testimonial Slider'),
            'description' => __('Customer testimonial slider.'),
            'template'    => '/template-parts/blocks/testimonial/testimonial_slider.php',
            'icon'        => 'format-quote',
            'keywords'    => ['testimonial', 'review'],
        ],
        [
            'name'        => 'image_slider',
            'title'       => __('Image Slider'),
            'description' => __('Product image slider.'),
            'template'    => '/template-parts/blocks/testimonial/image_slider.php',
            'icon'        => 'slides',
            'keywords'    => ['image', 'products', 'slider', 'carousel'],
        ],
        [
            'name'        => 'content_image_block',
            'title'       => __('Content Image Block'),
            'description' => __('A simple block to add image and content with reversable alignment.'),
            'template'    => '/template-parts/blocks/content-image-blocks/content_image_block.php',
            'icon'        => 'layout',
            'keywords'    => ['content', 'image', 'content image block'],
        ],
        [
            'name'        => 'content_image_block_2_images',
            'title'       => __('Content Image Block with 2 Images'),
            'description' => __('A customizable block to add an image on the left and content, including a list, on the right.'),
            'template'    => '/template-parts/blocks/content-image-blocks/content_image_block.php',
            'icon'        => 'layout',
            'keywords'    => ['content', 'image', 'content image block'],
        ],
        [
            'name'        => 'content_image_block_dark',
            'title'       => __('Content Image Block Dark'),
            'description' => __('A customizable block to add an image on the right and content, including an accordion on the left.'),
            'template'    => '/template-parts/blocks/content-image-blocks/content_image_block_dark.php',
            'icon'        => 'layout',
            'keywords'    => ['content', 'image', 'content image block'],
        ],
        [
            'name'        => 'content_video_block',
            'title'       => __('Content Video Block'),
            'description' => __('A customizable two-column block. Add content in one column and a video in the other.'),
            'template'    => '/template-parts/blocks/content-image-blocks/content_video_block.php',
            'icon'        => 'video-alt3',
            'keywords'    => ['content', 'videos', 'video', 'content video block'],
        ],
        [
            'name'        => 'shared_modal_trigger',
            'title'       => __('Shared Modal Trigger'),
            'description' => __('A customizable modal to add an image, video, or form to.'),
            'template'    => '/template-parts/blocks/creative-content-blocks/shared_modal_trigger.php',
            'icon'        => 'editor-customchar',
            'keywords'    => ['content', 'videos', 'video', 'content video block'],
        ],
        [
            'name'        => 'multiple_videos',
            'title'       => __('Multiple Videos'),
            'description' => __('A customizable block to add content and multiple videos in a grid.'),
            'template'    => '/template-parts/blocks/creative-content-blocks/multiple_videos.php',
            'icon'        => 'format-video',
            'keywords'    => ['content', 'videos', 'video', 'content video block'],
        ],
        [
            'name'        => 'fullwidth_image',
            'title'       => __('Full Width Image'),
            'description' => __('A customizable block to add a full-width image and overlaying content.'),
            'template'    => '/template-parts/blocks/content-image-blocks/fullwidth_image.php',
            'icon'        => 'format-image',
            'keywords'    => ['image', 'full width', 'full-width image', 'content over image'],
        ],
        [
            'name'        => 'pages_hero',
            'title'       => __('Pages Hero'),
            'description' => __('Use this masthead for pages other than the home page.'),
            'template'    => '/template-parts/blocks/hero/pages_hero.php',
            'icon'        => 'superhero',
            'keywords'    => ['hero', 'masthead', 'banner', 'pages hero'],
        ],
        [
            'name'        => 'accordion',
            'title'       => __('Accordion'),
            'description' => __('Accordion with Search Bar.'),
            'template'    => '/template-parts/blocks/accordion-blocks/accordion.php',
            'icon'        => 'yes',
            'keywords'    => ['accordion', 'faq', 'accordion with search', 'frequently asked questions'],
        ],
        [
            'name'        => 'accordion_2',
            'title'       => __('Accordion 2'),
            'description' => __('Accordion with an Aside.'),
            'template'    => '/template-parts/blocks/accordion-blocks/accordion_2.php',
            'icon'        => 'yes',
            'keywords'    => ['accordion', 'faq', 'accordion with aside', 'frequently asked questions'],
        ],
        [
            'name'        => 'masonry_portfolio',
            'title'       => __('Masonry Portfolio'),
            'description' => __('Portfolio to display images, text and categories.'),
            'template'    => '/template-parts/blocks/creative-content-blocks/masonry_portfolio.php',
            'icon'        => 'format-gallery',
            'keywords'    => ['gallery', 'masonry', 'images', 'portfolio', 'masonry portfolio'],
        ],

        [
            'name'        => 'content_block',
            'title'       => __('Content Block'),
            'description' => __('Block to add heading and text.'),
            'template'    => '/template-parts/blocks/creative-content-blocks/content_block.php',
            'icon'        => 'media-text',
            'keywords'    => ['content', 'heading', 'description', 'content block'],
        ],
        [
            'name'        => 'cards_side_by_side',
            'title'       => __('Cards Side by Side'),
            'description' => __('Block to add up to 4 cards side by side.'),
            'template'    => '/template-parts/blocks/cards/cards_side_by_side.php',
            'icon'        => 'columns',
            'keywords'    => ['cards', 'heading', 'description', 'icon'],
        ],
        [
            'name'        => 'content_image_slider',
            'title'       => __('Content Image Slider'),
            'description' => __('Block to add multiple content and images'),
            'template'    => '/template-parts/blocks/content-image-blocks/content_image_slider.php',
            'icon'        => 'slides',
            'keywords'    => ['content', 'image', 'slides'],
        ],
        [
            'name'        => 'sliding_cards',
            'title'       => __('Sliding Cards'),
            'description' => __('Block to add list of items with icons and images'),
            'template'    => '/template-parts/blocks/cards/sliding_cards.php',
            'icon'        => 'slides',
            'keywords'    => ['content', 'image', 'slides'],
        ],
        [
            'name'        => 'cards_team',
            'title'       => __('Team Cards'),
            'description' => __('Block to add team cards to the about page'),
            'template'    => '/template-parts/blocks/cards/cards_team.php',
            'icon'        => 'slides',
            'keywords'    => ['content', 'image', 'slides', 'about', 'team'],
        ],
        [
            'name'        => 'pdf_block',
            'title'       => __('PDF Block'),
            'description' => __('Display a call to action to download a PDF'),
            'template'    => '/template-parts/blocks/cta/pdf_block.php',
            'icon'        => 'slides',
            'keywords'    => ['pdf', 'cta', 'call to action', 'download'],
        ],
        [
            'name'        => 'parallax_block',
            'title'       => __('Parallax Block'),
            'description' => __('Background image with parallax effect and overlaying content'),
            'template'    => '/template-parts/blocks/cta/parallax_block.php',
            'icon'        => 'slides',
            'keywords'    => ['parallax', 'important content', 'image'],
        ],
        [
            'name'        => 'accordion_sidebar',
            'title'       => __('Accordion Sidebar'),
            'description' => __('Accordion with a sidebar for navigation'),
            'template'    => '/template-parts/blocks/accordion-blocks/accordion_sidebar.php',
            'icon'        => 'yes',
            'keywords'    => ['accordion', 'extended content', 'information', 'how-to'],
        ],
        [
            'name'        => 'template_block',
            'title'       => __('Template Block'),
            'description' => __('Dynamic block that displays all template tiles, links, and pdfs in a nested component'),
            'template'    => '/template-parts/blocks/accordion-blocks/template_block.php',
            'icon'        => 'yes',
            'keywords'    => ['extended content', 'templates', 'nested tiles'],
        ],
        [
            'name'        => 'contact_us_block',
            'title'       => __('Contact Us Block'),
            'description' => __('Contact Us Page Content and Settings'),
            'template'    => '/template-parts/blocks/contact-page/contact_us_block.php',
            'icon'        => 'yes',
            'keywords'    => ['contact', 'contact information', 'contact form'],
        ],
        [
            'name'        => 'case_studies_display',
            'title'       => __('Case Studies Display'),
            'description' => __('Display case studies'),
            'template'    => '/template-parts/blocks/post-displays/case_studies_display.php',
            'icon'        => 'images-alt2',
            'keywords'    => ['case studies', 'post display', 'cpt posts'],
        ],
        // Add more blocks here
    ];

    foreach ($blocks as $block) {
        acf_register_block_type([
            'name'            => $block['name'],
            'title'           => $block['title'],
            'description'     => $block['description'],
            'render_template' => get_template_directory() . $block['template'],
            'category'        => 'formatting',
            'icon'            => $block['icon'],
            'keywords'        => $block['keywords'],
            'mode'            => 'edit',
            'supports'        => [
                'align'   => true,
                'anchor'  => true,
                'mode'    => false
            ]
        ]);
    }
}
